### PR TITLE
docs: ❤️  Code is Poetry

### PR DESCRIPTION
**Pull request by ntwb**
This PR adds the "Code is Poetry" signature used throughout WordPress.org to each packages readme

codeispoetry-wide

### CODE REVIEW

**Comment by gziolo** [comment]
Why not this url: https://s.w.org/style/images/codeispoetry.png?1?

**Comment by ntwb** [comment]
The image I’ve used was sourced from that image and I added a left margin so that the image appears centred on GitHub README’s

**Comment by gziolo** [comment]
It’s not centered on mobile :) I think you can use img HTML code and GitHub will parse it properly.

**Comment by ntwb** [comment]
I've tried all the HTML tricks to have the image centered and cannot make it do so 😢 

I also tried the following Markdown tricks to no avail https://stackoverflow.com/q/3912694/1911294

I've pinged the #design team in Slack for some WordPress branding feedback 

https://wordpress.slack.com/archives/C02S78ZAL/p1519098547000130

**Comment by rmccue** [comment]
```html
<p align="center"><img src="https://s.w.org/style/images/codeispoetry.png?1" alt="Code is Poetry." /></p>
```

produces:

<p align="center">Code is Poetry.</p>

**Comment by ntwb** [comment]
Thanks @rmccue 💯

me: pretty much speechless 😞 😏

**Comment by rmccue** [comment]
Legacy attributes = 👌, `style` attribute or anything sane = 💩  😢

**Pull request merged**
